# Generated by Django 2.2.6 on 2019-12-11 23:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delegat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=20)),
                ('prezime', models.CharField(max_length=20)),
                ('datum_rodjenja', models.DateField(blank=True, null=True)),
                ('zvanje', models.CharField(max_length=200, null=True)),
                ('slika', models.ImageField(default='sudija.jpg', upload_to='delegat_img')),
            ],
            options={
                'verbose_name_plural': 'Delegati',
            },
        ),
        migrations.CreateModel(
            name='Obavestenja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=200)),
                ('sadrzaj', models.TextField(blank=True, null=True)),
                ('fajl', models.FileField(blank=True, null=True, upload_to='obavestenja')),
            ],
            options={
                'verbose_name_plural': 'Obaveštenja',
            },
        ),
        migrations.CreateModel(
            name='Odbor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_odbora', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Odbori',
            },
        ),
        migrations.CreateModel(
            name='Propisi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=200)),
                ('fajl', models.FileField(upload_to='propisi')),
            ],
            options={
                'verbose_name_plural': 'Propisi',
            },
        ),
        migrations.CreateModel(
            name='Sezona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sezona', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Sezone',
            },
        ),
        migrations.CreateModel(
            name='Sudija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=20)),
                ('prezime', models.CharField(max_length=20)),
                ('zvanje', models.CharField(max_length=200, null=True)),
                ('datum_rodjenja', models.DateField(blank=True, null=True)),
                ('slika', models.ImageField(default='sudija.jpg', upload_to='delegat_img')),
            ],
            options={
                'verbose_name_plural': 'Sudije',
            },
        ),
        migrations.CreateModel(
            name='Tim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Timovi',
            },
        ),
        migrations.CreateModel(
            name='TimoviSokobanja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=30)),
                ('ucesce', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='logo_img')),
            ],
            options={
                'verbose_name_plural': 'TimoviSokobanje',
            },
        ),
        migrations.CreateModel(
            name='TipSezone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Vest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=100)),
                ('sadrzaj', models.TextField()),
                ('vreme_posta', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Vesti',
                'ordering': ['-vreme_posta'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.CharField(blank=True, max_length=100, null=True)),
                ('vest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fudbal.Vest')),
            ],
            options={
                'verbose_name_plural': 'Videi',
            },
        ),
        migrations.CreateModel(
            name='Utakmica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolo', models.PositiveSmallIntegerField()),
                ('domacin_gol', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gost_gol', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('mesto_odigravanja', models.CharField(max_length=100)),
                ('datum_zakazano', models.DateTimeField(blank=True, null=True)),
                ('delegat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='delegat', to='fudbal.Delegat')),
                ('domacin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domacin', to='fudbal.Tim')),
                ('drugi_pomocnik', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='drug_pomocnik', to='fudbal.Sudija')),
                ('glavni_sudija', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='glavni_sudija', to='fudbal.Sudija')),
                ('gost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gost', to='fudbal.Tim')),
                ('prvi_pomocnik', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='prvi_pomocnik', to='fudbal.Sudija')),
                ('sezona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fudbal.Sezona')),
            ],
            options={
                'verbose_name_plural': 'Utakmice',
            },
        ),
        migrations.CreateModel(
            name='TimSezona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktivan', models.BooleanField(default=True)),
                ('sezona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fudbal.Sezona')),
                ('tim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fudbal.Tim')),
            ],
            options={
                'verbose_name_plural': 'Timovi u sezoni',
                'unique_together': {('sezona', 'tim')},
            },
        ),
        migrations.CreateModel(
            name='Slika',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=100)),
                ('vreme_posta', models.DateTimeField(default=django.utils.timezone.now)),
                ('slika', models.ImageField(default='default.jpg', upload_to='galerija_img')),
                ('vest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fudbal.Vest')),
            ],
            options={
                'verbose_name_plural': 'Slike',
                'ordering': ['-vreme_posta'],
            },
        ),
        migrations.AddField(
            model_name='sezona',
            name='tip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fudbal.TipSezone'),
        ),
        migrations.CreateModel(
            name='Kazne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kazneni_bodovi', models.PositiveSmallIntegerField()),
                ('razlog', models.TextField()),
                ('datum', models.DateField()),
                ('tim_u_sezoni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fudbal.TimSezona')),
            ],
            options={
                'verbose_name_plural': 'Kazneni bodovi',
            },
        ),
        migrations.CreateModel(
            name='ClanOdbora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funkcija', models.CharField(max_length=100)),
                ('ime', models.CharField(max_length=30)),
                ('prezime', models.CharField(max_length=30)),
                ('rezime', models.TextField(blank=True, null=True)),
                ('slika', models.ImageField(blank=True, null=True, upload_to='odbor_img')),
                ('odbor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fudbal.Odbor')),
            ],
            options={
                'verbose_name_plural': 'Clanovi odbora',
            },
        ),
        migrations.AlterUniqueTogether(
            name='sezona',
            unique_together={('sezona', 'tip')},
        ),
    ]
