# Generated by Django 2.1.7 on 2019-09-18 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sudija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime_sudije', models.CharField(max_length=20)),
                ('prezime_sudije', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime_tima', models.CharField(max_length=30)),
                ('odigrane_utakmice', models.PositiveSmallIntegerField(default=0)),
                ('broj_pobeda', models.PositiveSmallIntegerField(default=0)),
                ('broj_neresenih', models.PositiveSmallIntegerField(default=0)),
                ('broj_izgubljenih', models.PositiveSmallIntegerField(default=0)),
                ('dati_golovi', models.PositiveSmallIntegerField(default=0)),
                ('primljeni_golovi', models.PositiveSmallIntegerField(default=0)),
                ('gol_razlika', models.PositiveSmallIntegerField(default=0)),
                ('bodovi', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
