# Generated by Django 2.1.7 on 2019-09-19 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fudbal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utakmica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kolo', models.PositiveSmallIntegerField()),
                ('golovi_domacin', models.PositiveSmallIntegerField(default=0)),
                ('golovi_gost', models.PositiveSmallIntegerField(default=0)),
                ('sezona', models.CharField(default='2019/2020', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Utakmice',
            },
        ),
        migrations.AlterModelOptions(
            name='sudija',
            options={'verbose_name_plural': 'Sudije'},
        ),
        migrations.AlterModelOptions(
            name='tim',
            options={'verbose_name_plural': 'Timovi'},
        ),
        migrations.RemoveField(
            model_name='tim',
            name='bodovi',
        ),
        migrations.RemoveField(
            model_name='tim',
            name='broj_izgubljenih',
        ),
        migrations.RemoveField(
            model_name='tim',
            name='broj_neresenih',
        ),
        migrations.RemoveField(
            model_name='tim',
            name='broj_pobeda',
        ),
        migrations.RemoveField(
            model_name='tim',
            name='dati_golovi',
        ),
        migrations.RemoveField(
            model_name='tim',
            name='gol_razlika',
        ),
        migrations.RemoveField(
            model_name='tim',
            name='odigrane_utakmice',
        ),
        migrations.RemoveField(
            model_name='tim',
            name='primljeni_golovi',
        ),
        migrations.AddField(
            model_name='utakmica',
            name='drugi_sudija',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='drug_sudija', to='fudbal.Sudija'),
        ),
        migrations.AddField(
            model_name='utakmica',
            name='id_domacin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='domacin', to='fudbal.Tim'),
        ),
        migrations.AddField(
            model_name='utakmica',
            name='id_gost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='gost', to='fudbal.Tim'),
        ),
        migrations.AddField(
            model_name='utakmica',
            name='prvi_sudija',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='prvi_sudija', to='fudbal.Sudija'),
        ),
    ]
