# Generated by Django 2.2.6 on 2019-10-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fudbal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utakmica',
            name='sezona',
            field=models.PositiveSmallIntegerField(default=2019),
        ),
    ]
