# Generated by Django 2.2.6 on 2019-11-11 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fudbal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Odbor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_odbora', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Odbori',
            },
        ),
        migrations.CreateModel(
            name='ClanOdbora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funkcija', models.CharField(max_length=100)),
                ('ime', models.CharField(max_length=30)),
                ('prezime', models.CharField(max_length=30)),
                ('slika', models.ImageField(upload_to='odbor_img')),
                ('odbor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fudbal.Odbor')),
            ],
        ),
    ]
