# Generated by Django 2.1.7 on 2019-10-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fudbal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utakmica',
            name='sezona',
            field=models.CharField(max_length=10),
        ),
    ]
