# Generated by Django 2.2.6 on 2019-10-08 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fudbal', '0002_auto_20191006_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utakmica',
            name='delegat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='delegat', to='fudbal.Delegat'),
        ),
        migrations.AlterField(
            model_name='utakmica',
            name='drugi_pomocnik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='drug_pomocnik', to='fudbal.Sudija'),
        ),
        migrations.AlterField(
            model_name='utakmica',
            name='glavni_sudija',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='glavni_sudija', to='fudbal.Sudija'),
        ),
        migrations.AlterField(
            model_name='utakmica',
            name='prvi_pomocnik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='prvi_pomocnik', to='fudbal.Sudija'),
        ),
    ]
