# Generated by Django 2.1.7 on 2019-10-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fudbal', '0002_auto_20191001_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utakmica',
            name='sezona',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
