# Generated by Django 2.2.6 on 2019-11-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fudbal', '0002_clanodbora_odbor'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanodbora',
            name='rezime',
            field=models.TextField(blank=True, null=True),
        ),
    ]
