# Generated by Django 2.1.7 on 2019-10-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fudbal', '0003_auto_20191006_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utakmica',
            name='sezona',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
