# Generated by Django 2.2.6 on 2019-10-11 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fudbal', '0003_auto_20191009_0052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delegat',
            old_name='ime_delegata',
            new_name='ime',
        ),
        migrations.RenameField(
            model_name='delegat',
            old_name='prezime_delegata',
            new_name='prezime',
        ),
        migrations.RenameField(
            model_name='sudija',
            old_name='ime_sudije',
            new_name='ime',
        ),
        migrations.RenameField(
            model_name='sudija',
            old_name='prezime_sudije',
            new_name='prezime',
        ),
        migrations.RenameField(
            model_name='tim',
            old_name='ime_tima',
            new_name='ime',
        ),
    ]
