# Generated by Django 2.2.6 on 2019-11-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fudbal', '0003_clanodbora_rezime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clanodbora',
            name='slika',
            field=models.ImageField(blank=True, null=True, upload_to='odbor_img'),
        ),
    ]
