# Generated by Django 2.2.6 on 2019-11-13 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fudbal', '0004_auto_20191111_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clanodbora',
            options={'verbose_name_plural': 'Clanovi odbora'},
        ),
        migrations.RemoveField(
            model_name='utakmica',
            name='datum_odigrano',
        ),
    ]
