# Generated by Django 2.2.6 on 2019-11-03 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fudbal', '0004_auto_20191011_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegat',
            name='slika',
            field=models.ImageField(default='sudija.jpg', upload_to='delegat_img'),
        ),
        migrations.AddField(
            model_name='sudija',
            name='slika',
            field=models.ImageField(default='sudija.jpg', upload_to='delegat_img'),
        ),
    ]
