# Generated by Django 2.2.6 on 2019-11-03 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fudbal', '0005_auto_20191103_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='sudija',
            name='zvanje',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
