# Generated by Django 2.2.6 on 2019-11-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fudbal', '0005_auto_20191113_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obavestenja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=200)),
                ('fajl', models.FileField(upload_to='obavestenja')),
            ],
        ),
    ]
