# Generated by Django 2.2.6 on 2019-11-03 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fudbal', '0006_sudija_zvanje'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegat',
            name='zvanje',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
