# Generated by Django 2.2.6 on 2019-11-14 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fudbal', '0006_obavestenja'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='obavestenja',
            options={'verbose_name_plural': 'Obaveštenja'},
        ),
    ]
