# Generated by Django 2.2.6 on 2019-11-03 01:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fudbal', '0007_delegat_zvanje'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegat',
            name='datum_rodjenja',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sudija',
            name='datum_rodjenja',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
