# Generated by Django 2.2.6 on 2019-11-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fudbal', '0007_auto_20191114_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propisi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=200)),
                ('fajl', models.FileField(upload_to='propisi')),
            ],
            options={
                'verbose_name_plural': 'Propisi',
            },
        ),
    ]
