# Generated by Django 2.2.6 on 2019-11-03 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fudbal', '0008_auto_20191103_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sudija',
            name='datum_rodjenja',
            field=models.DateField(blank=True, null=True),
        ),
    ]
