# Generated by Django 2.2.6 on 2019-12-01 18:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fudbal', '0008_propisi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=100)),
                ('sadrzaj', models.TextField()),
                ('vreme_posta', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Vesti',
                'ordering': ['-vreme_posta'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.CharField(blank=True, max_length=100, null=True)),
                ('vest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fudbal.Vest')),
            ],
            options={
                'verbose_name_plural': 'Videi',
            },
        ),
        migrations.CreateModel(
            name='Slika',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=100)),
                ('vreme_posta', models.DateTimeField(default=django.utils.timezone.now)),
                ('slika', models.ImageField(default='default.jpg', upload_to='galerija_img')),
                ('vest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fudbal.Vest')),
            ],
            options={
                'verbose_name_plural': 'Slike',
                'ordering': ['-vreme_posta'],
            },
        ),
    ]
