# Generated by Django 2.2.6 on 2019-11-03 01:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fudbal', '0009_auto_20191103_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegat',
            name='datum_rodjenja',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sudija',
            name='datum_rodjenja',
            field=models.DateField(null=True),
        ),
    ]
