# Generated by Django 2.2.6 on 2019-11-05 01:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fudbal', '0011_auto_20191103_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kazne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kazneni_bodovi', models.PositiveSmallIntegerField()),
                ('razlog', models.TextField()),
                ('datum', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Sezona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sezona', models.PositiveSmallIntegerField()),
                ('tip', models.CharField(max_length=30)),
            ],
            options={
                'unique_together': {('sezona', 'tip')},
            },
        ),
        migrations.CreateModel(
            name='TimoviSokobanja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=30)),
                ('ucesce', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='logo_img')),
            ],
            options={
                'verbose_name_plural': 'Timovi',
            },
        ),
        migrations.CreateModel(
            name='TimSezona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktivan', models.BooleanField(default=True)),
                ('sezona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fudbal.Sezona')),
                ('tim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fudbal.TimoviSokobanja')),
            ],
        ),
        migrations.RenameField(
            model_name='utakmica',
            old_name='vreme_odigravanja',
            new_name='datum_odigrano',
        ),
        migrations.AddField(
            model_name='utakmica',
            name='datum_zakazano',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='utakmica',
            name='domacin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domacin', to='fudbal.TimoviSokobanja'),
        ),
        migrations.AlterField(
            model_name='utakmica',
            name='gost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gost', to='fudbal.TimoviSokobanja'),
        ),
        migrations.AlterField(
            model_name='utakmica',
            name='sezona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fudbal.Sezona'),
        ),
        migrations.DeleteModel(
            name='Tim',
        ),
        migrations.AddField(
            model_name='kazne',
            name='tim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fudbal.TimSezona'),
        ),
    ]
