# Generated by Django 2.2.6 on 2019-10-26 22:17

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slika',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=100)),
                ('vreme_posta', models.DateTimeField(default=django.utils.timezone.now)),
                ('slika', models.ImageField(default='default.jpg', upload_to='galerija_img')),
            ],
            options={
                'verbose_name_plural': 'Slika',
                'ordering': ['-vreme_posta'],
            },
        ),
        migrations.CreateModel(
            name='Vesti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=100)),
                ('sadrzaj', models.TextField()),
                ('vreme_posta', models.DateTimeField(default=django.utils.timezone.now)),
                ('slika', models.ImageField(default='default.jpg', upload_to='vesti_img')),
                ('video', models.FileField(blank=True, null=True, upload_to='vesti_video', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mkv', 'flv', 'avi'])])),
            ],
            options={
                'verbose_name_plural': 'Vesti',
                'ordering': ['-vreme_posta'],
            },
        ),
    ]
