# Generated by Django 2.2.6 on 2019-10-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vesti', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vesti',
            name='image',
        ),
        migrations.AddField(
            model_name='vesti',
            name='slika',
            field=models.ImageField(default='default.jpg', upload_to='vesti_img'),
        ),
    ]
