# Generated by Django 2.2.6 on 2019-10-26 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vesti', '0002_auto_20191027_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vesti',
            name='video',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
