# Generated by Django 2.2.6 on 2019-10-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vesti', '0002_auto_20191018_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galerija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=100)),
                ('vreme_posta', models.DateTimeField(auto_now_add=True)),
                ('slika', models.ImageField(default='default.jpg', upload_to='galerija_img')),
            ],
            options={
                'verbose_name_plural': 'Galerija',
                'ordering': ['-vreme_posta'],
            },
        ),
        migrations.AlterModelOptions(
            name='vesti',
            options={'ordering': ['-vreme_posta'], 'verbose_name_plural': 'Vesti'},
        ),
        migrations.AlterField(
            model_name='vesti',
            name='vreme_posta',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
