# Generated by Django 2.2.6 on 2019-10-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vesti', '0003_auto_20191025_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='vesti',
            name='video',
            field=models.ImageField(null=True, upload_to='vesti_video'),
        ),
    ]
