# Generated by Django 2.2.6 on 2019-10-26 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vesti', '0003_auto_20191027_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vesti',
            name='video',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
