# Generated by Django 2.2.6 on 2019-10-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vesti', '0005_auto_20191028_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vesti',
            name='video',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
