# Generated by Django 2.2.6 on 2019-10-25 23:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vesti', '0006_auto_20191026_0115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galerija',
            options={'ordering': ['-vreme_posta'], 'verbose_name_plural': 'Slika'},
        ),
        migrations.AlterField(
            model_name='vesti',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='vesti_video', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mkv', 'flv', 'avi'])]),
        ),
    ]
