# Generated by Django 2.2.6 on 2019-10-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vesti', '0006_auto_20191028_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vesti',
            name='video',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
