# Generated by Django 2.2.6 on 2019-11-01 00:01

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vesti', '0007_auto_20191029_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vesti',
            name='slika',
            field=imagekit.models.fields.ProcessedImageField(upload_to='avatars'),
        ),
    ]
