# Generated by Django 2.2.6 on 2019-10-25 23:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vesti', '0007_auto_20191026_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galerija',
            name='vreme_posta',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='vesti',
            name='vreme_posta',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
