# Generated by Django 2.2.6 on 2019-11-04 01:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vesti', '0007_auto_20191029_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=100)),
                ('sadrzaj', models.TextField()),
                ('vreme_posta', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Vesti',
                'ordering': ['-vreme_posta'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.CharField(blank=True, max_length=100, null=True)),
                ('vest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vesti.Vest')),
            ],
            options={
                'verbose_name_plural': 'Videi',
            },
        ),
        migrations.DeleteModel(
            name='Vesti',
        ),
        migrations.AlterModelOptions(
            name='slika',
            options={'ordering': ['-vreme_posta'], 'verbose_name_plural': 'Slike'},
        ),
        migrations.AddField(
            model_name='slika',
            name='vest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vesti.Vest'),
        ),
    ]
