# Generated by Django 2.2.6 on 2019-10-26 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vesti', '0008_auto_20191026_0132'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Galerija',
            new_name='Slika',
        ),
    ]
